# Generated by Django 3.0 on 2020-09-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_auto_20200914_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='celular',
            field=models.IntegerField(max_length=15),
        ),
    ]
